# Generated by Django 4.2.4 on 2023-08-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('date_of_birth', models.DateField()),
                ('room_number', models.IntegerField()),
                ('guardian_contact', models.CharField(max_length=15)),
                ('is_paid', models.BooleanField()),
            ],
        ),
    ]
