# Generated by Django 4.2.4 on 2023-08-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='fees_paid',
            field=models.FloatField(default=0.0),
        ),
    ]
