# Generated by Django 4.2.4 on 2023-08-03 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_fees_paid'),
    ]

    operations = [
    ]
