# Generated by Django 4.2.4 on 2023-08-03 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_alter_student_guardian_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
    ]
