# Generated by Django 4.2.4 on 2023-08-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_student_guardian_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hos_Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_num', models.CharField(max_length=20)),
                ('gender_required', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('current_members', models.IntegerField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='room_number',
            field=models.IntegerField(null=True),
        ),
    ]
