# Generated by Django 4.2.4 on 2023-08-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_remove_hos_rooms_current_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hos_rooms',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
    ]
