# Generated by Django 4.2.4 on 2023-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_hos_rooms_is_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hos_rooms',
            name='is_paid',
            field=models.IntegerField(),
        ),
    ]
