# Generated by Django 4.2.4 on 2023-08-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_alter_hos_rooms_is_paid'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hos_Rooms',
        ),
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
